##Mysql数据库配置
datasource:
  master:
    url: jdbc:mysql://60.205.212.196:3306/cloud-ida?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456


file:
  seeUrl: http://193.112.27.123:8012/disk/
