package com.example.controller;


import com.example.form.LoginForm;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * 菜单
 */
@RestController
@RequestMapping("/api/menu")
public class MenuController {

    @GetMapping("/menu")
    public String login(){
        String result = "{\n" +
                "    \"code\":200,\n" +
                "    \"msg\":\"\",\n" +
                "    \"data\":[\n" +
                "        {\n" +
                "            \"id\":\"120\",\n" +
                "            \"pid\":0,\n" +
                "            \"title\":\"工作台1111\",\n" +
                "            \"icon\":\"appstore-o\",\n" +
                "            \"url\":\"home\",\n" +
                "            \"file_path\":\"home\",\n" +
                "            \"params\":\"\",\n" +
                "            \"node\":\"#\",\n" +
                "            \"sort\":0,\n" +
                "            \"status\":1,\n" +
                "            \"create_by\":0,\n" +
                "            \"create_at\":\"2018-09-30 16:30:01\",\n" +
                "            \"is_inner\":false,\n" +
                "            \"values\":\"\",\n" +
                "            \"show_slider\":0,\n" +
                "            \"statusText\":\"使用中\",\n" +
                "            \"innerText\":\"导航\",\n" +
                "            \"fullUrl\":\"home\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"id\":\"121\",\n" +
                "            \"pid\":0,\n" +
                "            \"title\":\"项目管理\",\n" +
                "            \"icon\":\"project\",\n" +
                "            \"url\":\"#\",\n" +
                "            \"file_path\":\"#\",\n" +
                "            \"params\":\"\",\n" +
                "            \"node\":\"#\",\n" +
                "            \"sort\":0,\n" +
                "            \"status\":1,\n" +
                "            \"create_by\":0,\n" +
                "            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "            \"is_inner\":false,\n" +
                "            \"values\":\"\",\n" +
                "            \"show_slider\":1,\n" +
                "            \"statusText\":\"使用中\",\n" +
                "            \"innerText\":\"导航\",\n" +
                "            \"fullUrl\":\"#\",\n" +
                "            \"children\":[\n" +
                "                {\n" +
                "                    \"id\":\"122\",\n" +
                "                    \"pid\":121,\n" +
                "                    \"title\":\"项目列表\",\n" +
                "                    \"icon\":\"branches\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"151\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"我的项目\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/list\",\n" +
                "                            \"file_path\":\"project/list\",\n" +
                "                            \"params\":\":type\",\n" +
                "                            \"node\":\"project/project/index\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"my\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/list/my\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"163\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"项目分析\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/analysis\",\n" +
                "                            \"file_path\":\"project/analysis\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/index/info\",\n" +
                "                            \"sort\":5,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/analysis\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"155\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"我的收藏\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/list\",\n" +
                "                            \"file_path\":\"project/list\",\n" +
                "                            \"params\":\":type\",\n" +
                "                            \"node\":\"project/project/index\",\n" +
                "                            \"sort\":10,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"collect\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/list/collect\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"159\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"已归档项目\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/archive\",\n" +
                "                            \"file_path\":\"project/archive\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/project/index\",\n" +
                "                            \"sort\":10,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/archive\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"152\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"回收站\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/recycle\",\n" +
                "                            \"file_path\":\"project/recycle\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/project/index\",\n" +
                "                            \"sort\":20,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/recycle\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"127\",\n" +
                "                            \"pid\":122,\n" +
                "                            \"title\":\"我的组织\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"organization\",\n" +
                "                            \"file_path\":\"organization\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/organization/index\",\n" +
                "                            \"sort\":30,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"organization\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"156\",\n" +
                "                    \"pid\":121,\n" +
                "                    \"title\":\"基础设置\",\n" +
                "                    \"icon\":\"experiment\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"157\",\n" +
                "                            \"pid\":156,\n" +
                "                            \"title\":\"项目模板\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/template\",\n" +
                "                            \"file_path\":\"project/template\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/project_template/index\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"project/template\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"158\",\n" +
                "                            \"pid\":156,\n" +
                "                            \"title\":\"项目列表模板\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/template/taskStages\",\n" +
                "                            \"file_path\":\"project/template/taskStages\",\n" +
                "                            \"params\":\":code\",\n" +
                "                            \"node\":\"project/task_stages_template/index\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"project/template/taskStages\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"153\",\n" +
                "                    \"pid\":121,\n" +
                "                    \"title\":\"项目空间\",\n" +
                "                    \"icon\":\"heat-map\",\n" +
                "                    \"url\":\"project/space/task\",\n" +
                "                    \"file_path\":\"project/space/task\",\n" +
                "                    \"params\":\":code\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":20,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":true,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"内页\",\n" +
                "                    \"fullUrl\":\"project/space/task\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"154\",\n" +
                "                            \"pid\":153,\n" +
                "                            \"title\":\"任务详情\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/space/task/:code/detail\",\n" +
                "                            \"file_path\":\"project/space/taskdetail\",\n" +
                "                            \"params\":\":code\",\n" +
                "                            \"node\":\"project/task/read\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"project/space/task/:code/detail\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"162\",\n" +
                "                            \"pid\":153,\n" +
                "                            \"title\":\"项目文件\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/space/files\",\n" +
                "                            \"file_path\":\"project/space/files\",\n" +
                "                            \"params\":\":code\",\n" +
                "                            \"node\":\"project/index/info\",\n" +
                "                            \"sort\":10,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"project/space/files\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"161\",\n" +
                "                            \"pid\":153,\n" +
                "                            \"title\":\"项目概况\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"project/space/overview\",\n" +
                "                            \"file_path\":\"project/space/overview\",\n" +
                "                            \"params\":\":code\",\n" +
                "                            \"node\":\"project/index/info\",\n" +
                "                            \"sort\":20,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"project/space/overview\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"138\",\n" +
                "                    \"pid\":121,\n" +
                "                    \"title\":\"消息提醒\",\n" +
                "                    \"icon\":\"info-circle-o\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":30,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"139\",\n" +
                "                            \"pid\":138,\n" +
                "                            \"title\":\"站内消息\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"notify/notice\",\n" +
                "                            \"file_path\":\"notify/notice\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/notify/index\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"notify/notice\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"140\",\n" +
                "                            \"pid\":138,\n" +
                "                            \"title\":\"系统公告\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"notify/system\",\n" +
                "                            \"file_path\":\"notify/system\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/notify/index\",\n" +
                "                            \"sort\":10,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"notify/system\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ]\n" +
                "        },\n" +
                "        {\n" +
                "            \"id\":\"160\",\n" +
                "            \"pid\":0,\n" +
                "            \"title\":\"团队成员\",\n" +
                "            \"icon\":\"team\",\n" +
                "            \"url\":\"#\",\n" +
                "            \"file_path\":\"#\",\n" +
                "            \"params\":\"\",\n" +
                "            \"node\":\"#\",\n" +
                "            \"sort\":0,\n" +
                "            \"status\":1,\n" +
                "            \"create_by\":0,\n" +
                "            \"create_at\":null,\n" +
                "            \"is_inner\":true,\n" +
                "            \"values\":\"\",\n" +
                "            \"show_slider\":0,\n" +
                "            \"statusText\":\"使用中\",\n" +
                "            \"innerText\":\"内页\",\n" +
                "            \"fullUrl\":\"#\",\n" +
                "            \"children\":[\n" +
                "                {\n" +
                "                    \"id\":\"164\",\n" +
                "                    \"pid\":160,\n" +
                "                    \"title\":\"团队成员\",\n" +
                "                    \"icon\":\"\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":null,\n" +
                "                    \"is_inner\":true,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":0,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"内页\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"166\",\n" +
                "                            \"pid\":164,\n" +
                "                            \"title\":\"团队成员\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"members\",\n" +
                "                            \"file_path\":\"members\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/department/index\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"members\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"167\",\n" +
                "                            \"pid\":164,\n" +
                "                            \"title\":\"成员信息\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"members/profile\",\n" +
                "                            \"file_path\":\"members/profile\",\n" +
                "                            \"params\":\":code\",\n" +
                "                            \"node\":\"project/department/read\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":null,\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":0,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"members/profile\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ]\n" +
                "        },\n" +
                "        {\n" +
                "            \"id\":\"124\",\n" +
                "            \"pid\":0,\n" +
                "            \"title\":\"系统设置\",\n" +
                "            \"icon\":\"setting\",\n" +
                "            \"url\":\"#\",\n" +
                "            \"file_path\":\"#\",\n" +
                "            \"params\":\"\",\n" +
                "            \"node\":\"#\",\n" +
                "            \"sort\":100,\n" +
                "            \"status\":1,\n" +
                "            \"create_by\":0,\n" +
                "            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "            \"is_inner\":false,\n" +
                "            \"values\":\"\",\n" +
                "            \"show_slider\":1,\n" +
                "            \"statusText\":\"使用中\",\n" +
                "            \"innerText\":\"导航\",\n" +
                "            \"fullUrl\":\"#\",\n" +
                "            \"children\":[\n" +
                "                {\n" +
                "                    \"id\":\"143\",\n" +
                "                    \"pid\":124,\n" +
                "                    \"title\":\"系统管理\",\n" +
                "                    \"icon\":\"appstore\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"144\",\n" +
                "                            \"pid\":143,\n" +
                "                            \"title\":\"菜单路由\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"system/config/menu\",\n" +
                "                            \"file_path\":\"system/config/menu\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/menu/menuadd\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"system/config/menu\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"145\",\n" +
                "                            \"pid\":143,\n" +
                "                            \"title\":\"访问节点\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"system/config/node\",\n" +
                "                            \"file_path\":\"system/config/node\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/node/save\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"system/config/node\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"148\",\n" +
                "                    \"pid\":124,\n" +
                "                    \"title\":\"个人管理\",\n" +
                "                    \"icon\":\"user\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"149\",\n" +
                "                            \"pid\":148,\n" +
                "                            \"title\":\"个人设置\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"account/setting/base\",\n" +
                "                            \"file_path\":\"account/setting/base\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/index/editpersonal\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"account/setting/base\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"150\",\n" +
                "                            \"pid\":148,\n" +
                "                            \"title\":\"安全设置\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"account/setting/security\",\n" +
                "                            \"file_path\":\"account/setting/security\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/index/editpersonal\",\n" +
                "                            \"sort\":0,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"account/setting/security\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"168\",\n" +
                "                    \"pid\":124,\n" +
                "                    \"title\":\"测试菜单\",\n" +
                "                    \"icon\":\"\",\n" +
                "                    \"url\":\"admin/user/test\",\n" +
                "                    \"file_path\":\"admin/user/test\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"project/index/info\",\n" +
                "                    \"sort\":0,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":null,\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"admin/user/test\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"id\":\"125\",\n" +
                "                    \"pid\":124,\n" +
                "                    \"title\":\"成员管理\",\n" +
                "                    \"icon\":\"unlock\",\n" +
                "                    \"url\":\"#\",\n" +
                "                    \"file_path\":\"#\",\n" +
                "                    \"params\":\"\",\n" +
                "                    \"node\":\"#\",\n" +
                "                    \"sort\":10,\n" +
                "                    \"status\":1,\n" +
                "                    \"create_by\":0,\n" +
                "                    \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                    \"is_inner\":false,\n" +
                "                    \"values\":\"\",\n" +
                "                    \"show_slider\":1,\n" +
                "                    \"statusText\":\"使用中\",\n" +
                "                    \"innerText\":\"导航\",\n" +
                "                    \"fullUrl\":\"#\",\n" +
                "                    \"children\":[\n" +
                "                        {\n" +
                "                            \"id\":\"126\",\n" +
                "                            \"pid\":125,\n" +
                "                            \"title\":\"账号列表\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"system/account\",\n" +
                "                            \"file_path\":\"system/account\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/account/index\",\n" +
                "                            \"sort\":10,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"system/account\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"130\",\n" +
                "                            \"pid\":125,\n" +
                "                            \"title\":\"访问授权\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"system/account/auth\",\n" +
                "                            \"file_path\":\"system/account/auth\",\n" +
                "                            \"params\":\"\",\n" +
                "                            \"node\":\"project/auth/index\",\n" +
                "                            \"sort\":20,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":false,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"导航\",\n" +
                "                            \"fullUrl\":\"system/account/auth\"\n" +
                "                        },\n" +
                "                        {\n" +
                "                            \"id\":\"131\",\n" +
                "                            \"pid\":125,\n" +
                "                            \"title\":\"授权页面\",\n" +
                "                            \"icon\":\"\",\n" +
                "                            \"url\":\"system/account/apply\",\n" +
                "                            \"file_path\":\"system/account/apply\",\n" +
                "                            \"params\":\":id\",\n" +
                "                            \"node\":\"project/auth/apply\",\n" +
                "                            \"sort\":30,\n" +
                "                            \"status\":1,\n" +
                "                            \"create_by\":0,\n" +
                "                            \"create_at\":\"0000-00-00 00:00:00\",\n" +
                "                            \"is_inner\":true,\n" +
                "                            \"values\":\"\",\n" +
                "                            \"show_slider\":1,\n" +
                "                            \"statusText\":\"使用中\",\n" +
                "                            \"innerText\":\"内页\",\n" +
                "                            \"fullUrl\":\"system/account/apply\"\n" +
                "                        }\n" +
                "                    ]\n" +
                "                }\n" +
                "            ]\n" +
                "        }\n" +
                "    ],\n" +
                "    \"token\":\"371l1e2u2p2r1k2r2q1p2p342w2q1c302t1j2r34361e2s1i1j1d1d2q1e2v2r3835381h1f\"\n" +
                "}";
        return result;
    }
}
